#!/usr/bin/env python
# -*- coding: utf-8 -*-
#


import sys, optparse, logging

from openBMC.dbus_backend import Backend

def parse_argv():
    '''Parse command line arguments, and return (options, args) pair.'''

    parser = optparse.OptionParser()
    parser.add_option ('--debug', action='store_true',
        dest='debug', default=False,
        help='Enable debugging messages.')
    parser.add_option ('-l', '--logfile', type='string', metavar='FILE',
        dest='logfile', default=None,
        help='Write logging messages to a file instead to stderr.')
    (opts, args) = parser.parse_args()
    return (opts, args)

def setup_logging(debug=False, logfile=None):
    '''Setup logging.'''

    logging.raiseExceptions = False
    if debug:
        logging.basicConfig(level=logging.DEBUG, filename=logfile,
            format='%(asctime)s %(levelname)s: %(message)s')
    else:
        logging.basicConfig(level=logging.WARNING, filename=logfile,
            format='%(levelname)s: %(message)s')


argv_options, argv_args = parse_argv()
setup_logging(argv_options.debug, argv_options.logfile)


svr = Backend.create_dbus_server()
if not svr:
    logging.error("Error spawning DBUS server")
    sys.exit(10)
svr.run_dbus_service()